# TIMING -> Secs Mins Hrs DayOmonth Month DayOweek   https://godoc.org/github.com/robfig/cron

# [[ cronjob ]]
#   timing = "* * * * * *"  See link above
#   action = "bot function to execute"
#       current available actions are:
#           * pts - syncronize story points to screenful
#           * pr - scan PR(Uat) list for stale cards
#           * archive - archive old cards in Done and Backlog
#           * troll - fish through board for standard alerts (owners, points, stales)
#           * sprint - execute a new sprint
#           * holidays - check if its a holiday
#           * count-cards - count cards by theme in upcoming & ready for pts columns
#           * record-pts - record pts in current sprint by column into sql db
#           * epic-links - check and alert on feature cards not linked to epics
#   config = "name of toml file (minus extension) to run against"
  
### AUTOBOT CRONS ###
[[cronjob]]

    timing = "0 00 9 * * MON-FRI"
    action = "standupalert"
    config = "autobots"

[[cronjob]]

    timing = "0 20 9,15 * * *"
    action = "record-pts"
    config = "autobots"

[[cronjob]]

    timing = "0 15 10 * * MON-FRI"
    action = "critical-bug"
    config = "autobots"

[[cronjob]]

    timing = "0 45 8 * * MON-FRI"
    action = "holidays"
    config = "autobots"

[[cronjob]]

    timing = "0 15 9 * * MON-FRI"
    action = "pr-summary"
    config = "autobots"

[[cronjob]]

    timing = "0 30 8,12,15 * * MON-FRI"
    action = "points"
    config = "autobots"

[[cronjob]]

    timing = "0 34 8,12,15 * * MON-FRI"
    action = "troll"
    config = "autobots"
