# TOML file EXAMPLE.  All fields required.  Ask wall-e for help on finding trello UIDs

[general]

# General Info
        TeamName        = ""   # Name of your team WallE should refer to when talking in slack (instead of your board ID)
        Sprintname      = ""   # The Prefix for Sprint Names (current date is appeneded automagically) / toml filename needs to match this in lowercase
        TrelloOrg       = ""   # Short Team name for Trello Organization
        StaleTime       = 24   # Must be an integer in hours!!
        MaxPoints       = 8    # Points GREATER than this number are flagged as too large and will alert and fail automated card moves
	ArchiveDoneDays = 28   # Number of Days old a card should be in the Done column to be auto-archived
        BackLogDays     = 180  # Number of days before Wall*E archives a card in the backlog
        SprintDuration  = 14   # Duration of each sprint including weekends and holidays (IE 2 weeks == 14 days)    
        RetroActionDays = 9    # Number of days before Wall*E continues to complain to card owners about incomplete retro action items    
        IgnoreWeekends  = true # Ignore weekends when doing time based calculations for alerts
        HolidaySupport  = true # Ignore Holidays in the SQL DB walle_holidays table when alerting

# Trelloness - Requires Trello UID's Not "Names"
        BacklogID           = "" # Trello UID for your Backlog Column 
        Upcoming            = "" # Trello UID for your Upcoming/Un-Scoped Column
        Scoped              = "" # Trello UID for your Scoped Cards Column
        NextsprintID        = "" # Trello UID for your Next Sprint Column
        ReadyForWork        = "" # Trello UID for your Ready For Work Column
        Working             = "" # Trello UID for your Working Column
        ReadyForReview      = "" # Trello UID for your Waiting for Review or PR Column
        Done                = "" # Trello UID for your Done Column
        BoardID             = "" # Trello Board UID (found in board URL)
        ROLabelID           = "" # UID For label being used for ROLL-OVER flagging
        TemplateLabelID     = "" # UID For NCL Label being used to mark cards as Templates
        CfsprintID          = "" # The Custom Field UID for Sprint Name Field  (in trello MUST be text field)
        CfpointsID          = "" # The Custom Field UID for Card Points (in trello MUST be text field)
        retroCollectionID   = "" # The ID of the Collection you want to put your Retro Boards in. (Default for FRSaaS Team)
        AllowMembersLabel   = "" # The UID of the label that should cause alerting for "members on cards" to be supressed
        TrainingLabel       = "" # The UID of the label that should be used for training cards, this will suppress many normal process alerts
        SilenceCardLabel    = "" # The UID of the label that will silence 100% of wall-e in relation to that card and all alerts and actions
        DemoBoardID         = "" # The UID of the board that manages Demo cards.  This can be identical across TOML files

# Slackness
        RetroChannel        = "" # Channel to post Retro based info in (must start with @ or # per slack)
        SprintChannel       = "" # Channel to post sprint update messages (must start with @ or # per slack)
        ComplaintChannel    = "" # Channel to post PR and card issues/complaints (must start with @ or # per slack)

# Sprint Meeting Reminder Settings
        StandupAlertChannel = "" # Channel to post stand-up starting reminders
        StandupLink         = "" # Meeting link or URL for stand-up
        DemoAlertChannel    = "" # Channel to post Demo meeting start reminder 
        DemoAlertLink       = "" # Meeting link or URL for Demo Meeting
        RetroAlertChannel   = "" # Channel to post retro meeting start reminder
        RetroAlertLink      = "" # Meeting link or URL for Retro Meeting
        WDWAlertChannel     = "" # Channel to post WDW meeting start reminder
        WDWAlertLink        = "" # Meeting link or URL for WDW Meeting
